const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  onState: (cb) => ipcRenderer.on('media:state', (_e, m) => cb(m)),
  onArt: (cb) => ipcRenderer.on('media:art', (_e, m) => cb(m)),
  onPin: (cb) => ipcRenderer.on('win:pin-changed', (_e, on) => cb(on)),
  onSleep: (cb) => ipcRenderer.on('sleep:state', (_e, t) => cb(t)),
  onOwned: (cb) => ipcRenderer.on('store:owned', (_e, l) => cb(l)),
  storeInfo: () => ipcRenderer.invoke('store:info'),
  storeBuy: (id) => ipcRenderer.invoke('store:buy', id),
  storeRedeem: (key) => ipcRenderer.invoke('store:redeem', key),
  storeRestore: (email) => ipcRenderer.invoke('store:restore', email),
  dev: {
    info: () => ipcRenderer.invoke('dev:info'), devtools: () => ipcRenderer.send('dev:devtools'), asFree: (on) => ipcRenderer.send('dev:asfree', on),
    fakeUpdate: () => ipcRenderer.send('dev:fakeupdate'), screensaver: () => ipcRenderer.send('dev:screensaver'), signOut: () => ipcRenderer.send('dev:signout'),
  },
  onUpdate: (cb) => ipcRenderer.on('update:status', (_e, u) => cb(u)),
  updateState: () => ipcRenderer.invoke('update:state'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateInstall: () => ipcRenderer.send('update:install'),
  exportFile: (f) => ipcRenderer.invoke('file:export', f),
  ghost: (on) => ipcRenderer.send('win:ghost', !!on),
  onGhost: (cb) => ipcRenderer.on('ghost:state', (_e, on) => cb(!!on)),
  onScreensaver: (cb) => ipcRenderer.on('screensaver:request', () => cb()),
  screensaverState: (on) => ipcRenderer.send('screensaver:state', !!on),
  proStatus: () => ipcRenderer.invoke('pro:status'),
  artRejected: (key) => ipcRenderer.send('art:rejected', String(key)),
  onProStatus: (cb) => ipcRenderer.on('pro:status', (_e, s) => cb(s)),
  cmd: (c) => ipcRenderer.send('cmd', c),
  prefs: () => ipcRenderer.invoke('prefs:get'),
  setPrefs: (p) => ipcRenderer.send('prefs:set', p),
  lyrics: (m) => ipcRenderer.invoke('lyrics:get', m),
  toast: (t) => ipcRenderer.send('toast', t),
  sleep: (mins) => ipcRenderer.send('sleep:set', mins),
  close: () => ipcRenderer.send('win:close'),
  minimize: () => ipcRenderer.send('win:minimize'),
  minimizeWindow: () => ipcRenderer.send('win:minimizeWindow'),
  pin: (on) => ipcRenderer.send('win:pin', on),
  mini: (on) => ipcRenderer.send('win:mini', on),
  fullscreen: (on) => ipcRenderer.send('win:fullscreen', on),
});
